'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class A_Abono
    Public Property A_ID As Integer
    Public Property A_ID_Cho As Integer
    Public Property A_Monto_Abono As Integer
    Public Property A_Info_Vale As Nullable(Of Integer)

    Public Overridable Property Cho_Choferes As Cho_Choferes

End Class
