'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ca_Carreras
    Public Property Ca_ID As Integer
    Public Property Ca_Carrer As String

    Public Overridable Property Info_Informe_Barras As ICollection(Of Info_Informe_Barras) = New HashSet(Of Info_Informe_Barras)
    Public Overridable Property Zo_Zona As Zo_Zona

End Class
