'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cho_Choferes
    Public Property Cho_Cedula As Integer
    Public Property Cho_Num_Codigo As Integer
    Public Property Cho_Nombre As String
    Public Property Cho_Apellido1 As String
    Public Property Cho_Apellido2 As String
    Public Property Cho_Num_folio As Integer
    Public Property Cho_Boleta As Integer
    Public Property Cho_Compania As String

    Public Overridable Property A_Abono As ICollection(Of A_Abono) = New HashSet(Of A_Abono)
    Public Overridable Property Info_Informe_Barras As ICollection(Of Info_Informe_Barras) = New HashSet(Of Info_Informe_Barras)

End Class
