'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Pla_Planilla
    Public Property Plan_ID As Integer
    Public Property Pla_ID_Informes As Nullable(Of Integer)
    Public Property Pla_Saldo_Vales As Nullable(Of Double)
    Public Property Pla_Saldo_Sobrantes As Nullable(Of Double)
    Public Property Pla_Diferencia As Nullable(Of Double)
    Public Property Pla_Bonificacion As Nullable(Of Double)
    Public Property Pla_Monto_Reinte As Nullable(Of Double)
    Public Property Pla_Monto_Rebajar As Nullable(Of Double)

    Public Overridable Property Info_Informe_Barras As Info_Informe_Barras

End Class
