'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SistemaControl
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SistemaControl")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property A_Abono() As DbSet(Of A_Abono)
    Public Overridable Property Ca_Carreras() As DbSet(Of Ca_Carreras)
    Public Overridable Property Cho_Choferes() As DbSet(Of Cho_Choferes)
    Public Overridable Property Info_Informe_Barras() As DbSet(Of Info_Informe_Barras)
    Public Overridable Property Pla_Planilla() As DbSet(Of Pla_Planilla)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property U_Usuario() As DbSet(Of U_Usuario)
    Public Overridable Property Zo_Zona() As DbSet(Of Zo_Zona)

End Class
