'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class U_Usuario
    Public Property U_ID As Integer
    Public Property U_Usuario1 As String
    Public Property U_Contrasena As String
    Public Property U_ID_Zona As Nullable(Of Integer)

    Public Overridable Property Zo_Zona As Zo_Zona

End Class
