'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Zo_Zona
    Public Property Zo_ID As Integer
    Public Property Zo_Zona1 As String
    Public Property Zo_ID_Carrera As Nullable(Of Integer)

    Public Overridable Property Ca_Carreras As Ca_Carreras
    Public Overridable Property U_Usuario As ICollection(Of U_Usuario) = New HashSet(Of U_Usuario)

End Class
